apiVersion: v2
name: etcd-kubernetes-resources-count-exporter
version: 1.10.14
appVersion: 1.10.14
description: Collector that exposes metrics about k8s resources stored in etcd
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
home: "https://github.com/giantswarm/etcd-kubernetes-resources-count-exporter"
annotations:
  application.giantswarm.io/team: "turtles"
  config.giantswarm.io/version: 1.x.x
